-- One-time reset for the new receipt-number format (YYYYMM + 5-digit monthly
-- counter, e.g. 20260800001). This migration runs exactly once per database —
-- tracked by name in _app_migrations (see src/main/db/migrate.ts) — so it will
-- never re-run and never wipe data again after this release is first applied,
-- including on a pharmacy's real desktop install pulling this update.
--
-- Wipes every record that only exists because of a sale/receipt: Transaction,
-- TransactionItem, Refund, and the CreditLedgerEntry/LoyaltyPointEvent rows
-- generated BY a sale (transactionId IS NOT NULL). Standalone ledger/loyalty
-- activity not tied to any transaction (e.g. a manual funds-added credit) is
-- left alone, and its running balance is recomputed from what remains so it
-- stays internally consistent after the tied-to-a-sale rows are removed.

CREATE TABLE IF NOT EXISTS "ReceiptSequence" (
    "yearMonth" TEXT NOT NULL PRIMARY KEY,
    "lastNumber" INTEGER NOT NULL DEFAULT 0
);

DELETE FROM "Discount";

DELETE FROM "Refund";

DELETE FROM "LoyaltyPointEvent" WHERE "transactionId" IS NOT NULL;

DELETE FROM "CreditLedgerEntry" WHERE "transactionId" IS NOT NULL;

UPDATE "CreditLedgerEntry"
SET "balanceAfterCents" = (
  SELECT SUM("amountCents")
  FROM "CreditLedgerEntry" AS earlier
  WHERE earlier."customerId" = "CreditLedgerEntry"."customerId"
    AND (earlier."createdAt" < "CreditLedgerEntry"."createdAt"
         OR (earlier."createdAt" = "CreditLedgerEntry"."createdAt" AND earlier."id" <= "CreditLedgerEntry"."id"))
);

DELETE FROM "TransactionItem";

DELETE FROM "Transaction";
